# Generated by Django 3.2.14 on 2022-08-16 16:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scorerequest',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='scorerequest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.AddField(
        #     model_name='scorerequest',
        #     name='likes',
        #     field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AlterField(
            model_name='scorerequest',
            name='created_by',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='voting.scorerequest')),
            ],
        ),
    ]
