# Generated by Django 3.2.14 on 2022-08-15 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scorerequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scorerequest',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='scorerequest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scorerequest',
            name='like_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
