# Generated by Django 3.2.14 on 2022-08-15 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0002_auto_20220815_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerequest',
            name='like_list',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='like_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
