# Generated by Django 3.2.14 on 2022-08-12 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0002_auto_20220812_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
