# Generated by Django 3.2.14 on 2022-08-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_scorerequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerequest',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
