# Generated by Django 3.2.14 on 2022-08-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_scorerequest_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorerequest',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='scorerequest',
            name='score',
        ),
    ]
