# Generated by Django 3.2.14 on 2022-08-15 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0005_auto_20220815_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerequest',
            name='like_list',
            field=models.ManyToManyField(related_name='like_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
