# Generated by Django 3.2.14 on 2022-08-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20220816_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketracker',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
