# Generated by Django 3.2.14 on 2022-08-15 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0006_scorerequest_like_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerequest',
            name='like_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='like_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
