# Generated by Django 3.2.14 on 2022-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_auto_20220830_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerequest',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
