# Generated by Django 3.2.14 on 2022-09-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_auto_20220908_1350'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Comment',
        # ),
    ]
