# Generated by Django 3.2.14 on 2022-09-08 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0017_alter_scorerequest_likes'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='scorerequest',
        #     name='likes',
        # ),
        migrations.AddField(
            model_name='scorerequest',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        # migrations.DeleteModel(
        #     name='Comment',
        # ),
    ]
