# Generated by Django 3.2.14 on 2022-09-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_auto_20220908_1400'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='scorerequest',
        #     name='likes',
        # ),
        # migrations.DeleteModel(
        #     name='Comment',
        # ),
    ]
