# Generated by Django 3.2.14 on 2022-09-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_auto_20220911_1512'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='scorerequest',
        #     name='likes',
        # ),
        # migrations.DeleteModel(
        #     name='Comment',
        # ),
    ]
