# Generated by Django 3.2.14 on 2022-09-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0022_auto_20220916_1614'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='scorerequest',
        #     name='likes',
        # ),
        # migrations.DeleteModel(
        #     name='Comment',
        # ),
    ]
