# Generated by Django 3.2.14 on 2022-10-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0023_auto_20220919_1157'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='scorerequest',
        #     name='likes',
        # ),
        # migrations.DeleteModel(
        #     name='Comment',
        # ),
    ]
