# Generated by Django 3.2.14 on 2022-10-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0024_auto_20221007_2041'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='scorerequest',
        #     name='likes',
        # ),
        # migrations.DeleteModel(
        #     name='Comment',
        # ),
    ]
