# Generated by Django 3.2.14 on 2022-07-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_purchased_scores'),
        ('checkout', '0002_auto_20220718_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user_profile.userprofile'),
        ),
    ]
