# Generated by Django 3.2.14 on 2022-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
