# Generated by Django 3.2.14 on 2022-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purchased_scores',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
