# Generated by Django 3.2.14 on 2022-07-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_purchased_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='purchased_scores',
        ),
    ]
