# Generated by Django 3.2.14 on 2022-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20220809_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='money_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
