# Generated by Django 3.2.14 on 2022-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
