# Generated by Django 3.2.14 on 2022-07-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220712_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Guitar_Pro',
            field=models.FileField(null=True, upload_to='../static/media/'),
        ),
    ]
