# Generated by Django 3.2.14 on 2022-07-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_category_product_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genres'},
        ),
    ]
