# Generated by Django 3.2.14 on 2022-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220804_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
