# Generated by Django 3.2.14 on 2022-09-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_number_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
